'use strict';
let language='ja';
const messages={
ja:{title:'教室ルーレット',language:'言語',sound:'音を鳴らす',turn:'さあ、だれの番？',fair:'どの選択肢も、同じ確率。',choices:'選択肢',help:'1行に1つ。コピー＆ペーストもできます。',blank:'空の行は無視されます',clear:'すべて消す',auto:'当たった項目を自動で除外',autoHelp:'同じ項目が続けて当たらないようにします',reset:'リセット',resetHelp:'選択肢と設定を初期状態に戻します（1〜6）',footer:'教室の、ちいさなくじ引き。',selected:'選ばれたのは',continue:'つづける',placeholder:'ここに選択肢を入力\n1行につき1つ',wheel:'ルーレット',wheelButton:'ルーレットを回す',chips:'個別に削除',count:n=>`${n} 項目`,spinning:'抽選中',spin:'まわす',add:'入力してね',delete:n=>`${n}を削除`,changed:'選択肢を変更しました',empty:'選択肢を入力してください',waiting:'どれに当たるかな…',won:n=>`「${n}」が当たりました`,removed:n=>`この項目を除外しました。残り ${n} 項目です。`,finished:'すべての抽選が終わりました。新しい選択肢を入力してください。',again:'もう一度、ルーレットを回せます。',start:'ルーレットを押してスタート',resetDone:'リセットしました。もう一度どうぞ！'},
en:{title:'Classroom Wheel',language:'Language',sound:'Sound on',turn:'Whose turn is it?',fair:'Every option has an equal chance.',choices:'Options',help:'One option per line. Copy and paste works too.',blank:'Blank lines are ignored',clear:'Clear all',auto:'Remove the selected option',autoHelp:'Each option can only be selected once',reset:'Reset',resetHelp:'Restore default options and settings (1–6)',footer:'A little lucky draw for the classroom.',selected:'The selected option is',continue:'Continue',placeholder:'Enter options here\nOne per line',wheel:'Wheel',wheelButton:'Spin the wheel',chips:'Remove individual options',count:n=>`${n} option${n===1?'':'s'}`,spinning:'Spinning',spin:'Spin',add:'Add options',delete:n=>`Remove ${n}`,changed:'Options updated',empty:'Enter some options to get started',waiting:'Which one will it be…?',won:n=>`Selected: ${n}`,removed:n=>`This option was removed. ${n} remaining.`,finished:'All options have been selected. Enter new options to play again.',again:'You can spin the wheel again.',start:'Press the wheel to start',resetDone:'Reset complete. Ready to spin!'},
vi:{title:'Vòng quay lớp học',language:'Ngôn ngữ',sound:'Bật âm thanh',turn:'Đến lượt ai nào?',fair:'Mỗi lựa chọn đều có cơ hội như nhau.',choices:'Các lựa chọn',help:'Mỗi dòng một lựa chọn. Có thể sao chép và dán.',blank:'Các dòng trống sẽ được bỏ qua',clear:'Xóa tất cả',auto:'Tự động loại bỏ mục đã được chọn',autoHelp:'Mỗi mục chỉ được chọn một lần',reset:'Đặt lại',resetHelp:'Khôi phục lựa chọn và cài đặt mặc định (1–6)',footer:'Một vòng quay may mắn cho lớp học.',selected:'Mục được chọn là',continue:'Tiếp tục',placeholder:'Nhập các lựa chọn tại đây\nMỗi dòng một mục',wheel:'Vòng quay',wheelButton:'Quay vòng quay',chips:'Xóa từng lựa chọn',count:n=>`${n} mục`,spinning:'Đang quay',spin:'Quay',add:'Nhập mục',delete:n=>`Xóa ${n}`,changed:'Đã cập nhật các lựa chọn',empty:'Hãy nhập các lựa chọn để bắt đầu',waiting:'Sẽ là mục nào đây…?',won:n=>`Đã chọn: ${n}`,removed:n=>`Đã loại bỏ mục này. Còn lại ${n} mục.`,finished:'Tất cả các mục đã được chọn. Hãy nhập các lựa chọn mới để chơi tiếp.',again:'Bạn có thể quay thêm lần nữa.',start:'Nhấn vào vòng quay để bắt đầu',resetDone:'Đã đặt lại. Sẵn sàng quay!'}
};
function tr(key,...args){const value=messages[language][key];return typeof value==='function'?value(...args):value;}
function setLanguage(value){
 language=Object.hasOwn(messages,value)?value:'ja';
 document.documentElement.lang=language;document.title=tr('title');
 document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));
 document.getElementById('entries').placeholder=tr('placeholder');
 document.querySelector('.stage').setAttribute('aria-label',tr('wheel'));
 document.getElementById('wheelButton').setAttribute('aria-label',tr('wheelButton'));
 document.getElementById('chips').setAttribute('aria-label',tr('chips'));
}
